[package]
name = "poker-types"
version.workspace = true
edition.workspace = true

[dependencies]
async-graphql.workspace = true
linera-sdk.workspace = true
serde.workspace = true
serde_json.workspace = true
